### ISSUE TITLE
How to extend generated Builder with default property values

### ISSUE THREAD

**Issue by fbridger** [dasMulli/data-builder-generator#5]
Hi, great job developing this builder source generator.

I started looking at it and I am wondering how could we extend the generated Builder so we can initialize some of the properties with default values (e.g. hardcoded)

```csharp
var martin = new PersonBuilder().Build();

// So the generated instance already have this information
martin.FirstName.Should().Be("Martin");
martin.MiddleName.Should().Be("Andreas");
martin.LastName.Should().Be("Ullrich");
```

I would love to collaborate and get this feature included with some of your help.

**Comment by fabionaspolini** [comment]
I think this is coded at the initialization of the data class.

```csharp
[GenerateDataBuilder]
    public class Person
    {
        public string FirstName { get; set; }
        public string? MiddleNames { get; set; } = "Initial value"; // <===== Here
        public string LastName { get; set; }

        public Person(string firstName, string lastName)
        {
            FirstName = firstName;
            LastName = lastName;
        }
    }
```

**Comment by fbridger** [comment]
Correct. You could potentially add default values to the original class. However, I would like to set the default values when the Builder gets created as this is only used in our Unit Tests.

I ended up adding a Init() method as a partial class. However, I would prefer that the ctor() of the Builder doesn't get generated so we can use that.

```csharp
[GenerateDataBuilder]
public class Person
{
    public string FirstName { get; set; }
    public string? MiddleNames { get; set; }
    public string LastName { get; set; }
}

public partial class PersonBuilder 
{
    public PersonBuilder Init() {
        _firstName = "Homer";
        _middleNames = "J.";
        _lastName = "Simpson";
        return this;
    }
}
```

**Comment by dasMulli** [comment]
(Between vacations now, sorry)

What I usually do is a `PersonBuilder.Default.With…()…Build()` by doing something similar to:

```
public partial class PersonBuilder
{
    public static PersonBuilder Default => new PersonBuilder().WithMiddleName(„initial value“);
}
```

I‘m not sure if there is a good / clean way to encode that in the source but open to suggestions. (Do note that this generator is (over-)due for a bit of a rewrite now that there are better testing APIs and more experience with source generators)

**Comment by fbridger** [comment]
Thanks @dasMulli for providing that. Great library and awesome work!
